/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.cdc.connectors.kafkajson.source.connection;

import io.debezium.jdbc.JdbcConfiguration;
import io.debezium.jdbc.JdbcConnection;
import io.debezium.jdbc.JdbcConnection.ConnectionFactory;
import io.debezium.relational.Column;
import io.debezium.relational.ColumnEditor;
import io.debezium.relational.TableId;
import io.debezium.relational.Tables.ColumnNameFilter;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Optional;

/**
 * A {@link JdbcConnection} whose column-metadata read skips the column default value.
 *
 * <p>{@link JdbcConnection#readTableColumn} fetches {@code COLUMN_DEF} ({@code getString(13)}) first
 * and feeds it into Debezium's {@code TableSchemaBuilder} as the {@code defaultValueExpression}. For
 * binary-typed columns the MySQL driver reports the default as a literal string ({@code 0x} for a
 * {@code BINARY DEFAULT 0x...}, or raw binary bytes on TiDB), which {@code SchemaBuilder.defaultValue}
 * refuses to convert into a {@code BYTES} default and aborts the whole schema read with {@code
 * DebeziumException: Failed to set field default value ...}. This connector resolves column defaults
 * itself (see the DDL parser), so the JDBC-snapshot path never needs the driver-provided default and
 * the fetch is skipped entirely.
 */
public class KafkaJsonJdbcConnection extends JdbcConnection {

    public KafkaJsonJdbcConnection(
            JdbcConfiguration config,
            ConnectionFactory connectionFactory,
            String openingQuoteCharacter,
            String closingQuoteCharacter) {
        super(config, connectionFactory, openingQuoteCharacter, closingQuoteCharacter);
    }

    /**
     * Replicates {@link JdbcConnection#readTableColumn} without reading the {@code COLUMN_DEF} default
     * value: the MySQL driver returns it as a literal that Debezium cannot convert into a typed schema
     * default for binary (and some other) types, failing the schema read (see the class javadoc).
     */
    @Override
    protected Optional<ColumnEditor> readTableColumn(
            ResultSet columnMetadata, TableId tableId, ColumnNameFilter columnFilter)
            throws SQLException {
        final String columnName = columnMetadata.getString(4);
        if (columnFilter == null
                || columnFilter.matches(
                        tableId.catalog(), tableId.schema(), tableId.table(), columnName)) {
            ColumnEditor column = Column.editor().name(columnName);
            column.type(columnMetadata.getString(6));
            column.length(columnMetadata.getInt(7));
            if (columnMetadata.getObject(9) != null) {
                column.scale(columnMetadata.getInt(9));
            }
            column.optional(isNullable(columnMetadata.getInt(11)));
            column.position(columnMetadata.getInt(17));
            column.autoIncremented("YES".equalsIgnoreCase(columnMetadata.getString(23)));
            String autogenerated = null;
            try {
                autogenerated = columnMetadata.getString(24);
            } catch (SQLException e) {
                // ignore, some drivers don't have this index
            }
            column.generated("YES".equalsIgnoreCase(autogenerated));

            column.nativeType(resolveNativeType(column.typeName()));
            column.jdbcType(resolveJdbcType(columnMetadata.getInt(5), column.nativeType()));

            // Allow implementation to make column changes if required before being added to table
            column = overrideColumn(column);

            // Column default is intentionally not read (no getString(13) / defaultValueExpression).
            return Optional.of(column);
        }

        return Optional.empty();
    }
}
